### ISSUE TITLE
Eclipse Egit pull fails because of the libery maven plugin 

### ISSUE THREAD

**Issue by argenstijn** [OpenLiberty/open-liberty-tools#240]
**Context:**
When i try to do a GIT Pull in Eclipse it fails because it cannot rename the POM

Exception caught during execution of merge command. java.io.IOException: Could not rename file C:\Users\......\git\APIController\._pom.xml5047232869218576831.tmp to C:\Users\......\git\APIController\pom.xml
Exception caught during execution of merge command. java.io.IOException: Could not rename file C:\Users\......\git\APIController\._pom.xml5047232869218576831.tmp to C:\Users\......\git\APIController\pom.xml

**Software:**

-Eclipse Java EE IDE for Web Developers.
Version: Photon Release (4.8.0)
Build id: 20180619-1200

-WebSphere® Application Server Liberty Tools	18.0.2000.v20180627_2035	
-Git integration for Eclipse	5.0.0.201806131550-r

**Cause (probably)**

#151 C:\Users\........\git\APIController\pom.xml by thread:main on Fri Sep 14 12:22:19 CEST 2018
	at java.io.FileInputStream.<init>(FileInputStream.java:139)
	at com.ibm.etools.maven.liberty.integration.manager.internal.MavenProjectInspector.getModelObject(MavenProjectInspector.java:148)
	at com.ibm.etools.maven.liberty.integration.manager.internal.MavenProjectInspector.isSupportedProject(MavenProjectInspector.java:106)
	at com.ibm.etools.maven.liberty.integration.internal.LibertyMaven.isSupportedProject(LibertyMaven.java:184)
	at com.ibm.ws.st.liberty.buildplugin.integration.ui.actions.internal.AbstractLibertyIntegrationPropertyTester.test(AbstractLibertyIntegrationPropertyTester.java:33)
	at org.eclipse.core.internal.expressions.Property.test(Property.java:58)
	at org.eclipse.core.internal.expressions.TestExpression.evaluate(TestExpression.java:100)
	at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:51)
	at org.eclipse.core.internal.expressions.EnablementExpression.evaluate(EnablementExpression.java:55)
	at org.eclipse.ui.internal.ObjectActionContributor$ObjectContribution.isApplicableTo(ObjectActionContributor.java:368)
	at org.eclipse.ui.internal.ObjectActionContributor.isApplicableTo(ObjectActionContributor.java:238)
	at org.eclipse.ui.internal.ObjectContributorManager.isApplicableTo(ObjectContributorManager.java:301)
	at org.eclipse.ui.internal.ObjectActionContributorManager.contributeObjectActions(ObjectActionContributorManager.java:89)
	at org.eclipse.ui.internal.PopupMenuExtender.addObjectActions(PopupMenuExtender.java:317

**See also**
 https://stackoverflow.com/questions/47105159/locked-pom-xml-causes-git-branch-checkout-failure-in-eclipse

**Comment by argenstijn** [comment]
Hi there. Any news about solving this issue? Very irritating this bug!.

**Comment by argenstijn** [comment]
com.ibm.etools.maven.liberty.integration.manager.internal.MavenProjectInspector.getModelObject(MavenProjectInspector.java:148)

Why does this not close the inputstream after reading? PLease fix this? 1 min work!

**Comment by eharris369** [comment]
I have put in a PR for this: #262.  If it fixes the problem then please close this issue.

**Comment by argenstijn** [comment]
It fixes this issue. Already tested it. 

I advise to use this code:

private Model getModelObject(IFile pomFile) {

        if (pomFile == null) {
            if (Trace.ENABLED)
                Trace.trace(Trace.WARNING, "A pom file was not specified before attempting to create the model");
            return null;
        }
        if (!pomFile.exists()) {
            if (Trace.ENABLED)
                Trace.trace(Trace.WARNING, "The pom file cannot be found: " + pomFile.getLocation().toOSString());
            return null;
        }

        MavenXpp3Reader reader = new MavenXpp3Reader();

        try (Reader inputReader = new InputStreamReader(new FileInputStream(pomFile.getLocation().toFile()))) {
            return reader.read(inputReader);
        } catch (IOException | XmlPullParserException e) {
            Trace.logError("The pom file could not be read", e);
        }

        return null;

    }
