### ISSUE TITLE
Display error message when module fails to publish

### ISSUE THREAD

**Issue by johnmcollier** [OpenLiberty/open-liberty-tools#29]
Currently if a module fails to publish on to a server, a NPE will be thrown without any further information as to which module failed to publish. A solution is to wrap the call to either publishDir in JEEPublisher.publishModule (or the call to publishSmart in ApplicationPublisher.publishDir) with a try/catch and print out an error message informing the user which module failed to publish. 

**Example Stack Trace:**
```
java.lang.NullPointerException
at org.eclipse.wst.server.core.util.PublishHelper.publishSmart(PublishHelper.java:331)
at org.eclipse.wst.server.core.util.PublishHelper.publishSmart(PublishHelper.java:367)
at org.eclipse.wst.server.core.util.PublishHelper.publishSmart(PublishHelper.java:367)
at org.eclipse.wst.server.core.util.PublishHelper.publishSmart(PublishHelper.java:188)
at com.ibm.ws.st.core.internal.ApplicationPublisher.publishDir(ApplicationPublisher.java:886)
at com.ibm.ws.st.jee.core.internal.JEEPublisher.publishModule(JEEPublisher.java:170)
at com.ibm.ws.st.core.internal.ApplicationPublisher.publishModuleAndChildren(ApplicationPublisher.java:147)
at com.ibm.ws.st.core.internal.ApplicationPublisher.publishModuleAndChildren(ApplicationPublisher.java:153)
at com.ibm.ws.st.core.internal.ServerExtensionWrapper.publishModuleAndChildren(ServerExtensionWrapper.java:358)
at com.ibm.ws.st.core.internal.WebSphereServerBehaviour.publishApplication(WebSphereServerBehaviour.java:1195)
at com.ibm.ws.st.core.internal.WebSphereServerBehaviour.publishModules(WebSphereServerBehaviour.java:946)
at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:987)
at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3172)
at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:345)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by johnmcollier** [comment]
@eharris369 Assigning this to you since this seems to be server tools change that needs to be made, feel free to reassign if necessary.

**Comment by johnmcollier** [comment]
**Potential fix:**
Change line 168 in JEEPublisher.publishModule from:
`publishDir(kind, unit.getDeltaKind(), module, getDeployPath(module, false), helper, status, monitor);`

to:
```
try {
                            publishDir(kind, unit.getDeltaKind(), module, getDeployPath(module, false), helper, status, monitor);
                        } catch (NullPointerException e) {
                            status.add(new Status(IStatus.ERROR, Activator.PLUGIN_ID, NLS.bind(Messages.errorPublishingModule, module[size - 1].getModuleType().)));
                            e.printStackTrace();
                        }
```
