### ISSUE TITLE
DeadLock Starting Eclipse 2018-12R

### ISSUE THREAD

**Issue by seamusmac** [OpenLiberty/open-liberty-tools#293]
I have 3 Liberty servers configured in my eclipse workspace, testing JMS, RMI replication etc.
However I keep getting a deadlock when starting.

I have include the output from jstack when the deadlock happens. It can be seen at
https://gist.github.com/seamusmac/c4e6daa82c9be0d17dda42bce5e06bc1

If you need anything else, or maybe its an eclipse bug. I'm not sure

**Comment by eharris369** [comment]
This is another case of code that is working with a particular runtime but then calls a method that loops through all of the runtimes to get some information leading to deadlocks.  In this case it is trying to resolve an include file in the server configuration.  The code needs to be modified to only look in the current runtime.  The stack trace is:

       at com.ibm.ws.st.core.internal.WebSphereRuntime.getWebSphereServerInfos(WebSphereRuntime.java:745)
        - waiting to lock <0x000000008a24b078> (a com.ibm.ws.st.core.internal.WebSphereRuntime)
        at com.ibm.ws.st.core.internal.WebSphereUtil.getWebSphereServerInfos(WebSphereUtil.java:149)
        at com.ibm.ws.st.core.internal.config.ConfigUtils.getDOM(ConfigUtils.java:816)
        at com.ibm.ws.st.core.internal.config.ConfigUtils.getResolvedElements(ConfigUtils.java:1406)
        at com.ibm.ws.st.core.internal.config.ConfigUtils.getResolvedElements(ConfigUtils.java:1356)
        at com.ibm.ws.st.core.internal.config.ConfigUtils.getResolvedElements(ConfigUtils.java:1343)
        at com.ibm.ws.st.core.internal.config.ConfigurationFile.getApplications(ConfigurationFile.java:715)
        - locked <0x000000008fe8a578> (a com.ibm.ws.st.core.internal.WebSphereRuntime)
at com.ibm.ws.st.core.internal.WebSphereServerBehaviour.syncExternalModules(WebSphereServerBehaviour.java:254)
