### ISSUE TITLE
DockerUtilitiesTest failing on testSSLCertificate

### ISSUE THREAD

**Issue by GeekArthur** [OpenLiberty/open-liberty-tools#309]
The 'DockerUtilitiesTest' is failing with the exception listed below. It is not specific to any version of Java, or any version of Eclipse, and has been failing since March 30th (as per Couplet test result history.) I verified that the remote Docker VM used by the test is working as expected.

Failing on 'DockerUtilitiesTest.testSSLCertificate' with:

java.lang.AssertionError: Error creating SSL certificate: The utility did not complete. See the workspace log file for details.
    at com.ibm.ws.st.core.tests.DockerUtilitiesTest.testSSLCertificate(DockerUtilitiesTest.java:128)
    at org.eclipse.swtbot.eclipse.junit.headless.EclipseTestRunner.run(EclipseTestRunner.java:350)
    at org.eclipse.swtbot.eclipse.junit.headless.EclipseTestRunner.run(EclipseTestRunner.java:208)
    at org.eclipse.swtbot.eclipse.junit.headless.UITestApplication.runTests(UITestApplication.java:120)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$$Lambda$147.0000000052241020.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:812)

**Comment by GeekArthur** [comment]
Already fixed in the PR, close this issue.
