### ISSUE TITLE
An internal error occurred during: "Validating" due to class not found issue Eclipse 2023-03

### ISSUE THREAD

**Issue by wnm3** [OpenLiberty/open-liberty-tools#476]
I'm getting the following error running the latest version of Eclipse (2023-03) on M1 arm64 MacBook:

java.lang.NoClassDefFoundError: org/eclipse/m2e/wtp/MavenWtpPlugin
	at com.ibm.etools.maven.javaee.ui.validation.MavenProjectSettingsValidator.getCurrentMavenPreferences(MavenProjectSettingsValidator.java:358)
	at com.ibm.etools.maven.javaee.ui.validation.MavenProjectSettingsValidator.hasStandardProjectSettings(MavenProjectSettingsValidator.java:205)
	at com.ibm.etools.maven.javaee.ui.validation.MavenProjectSettingsValidator.validateProjectSettings(MavenProjectSettingsValidator.java:125)
	at com.ibm.etools.maven.javaee.ui.validation.MavenProjectSettingsValidator.validate(MavenProjectSettingsValidator.java:88)
	at org.eclipse.wst.validation.Validator$V2.validate(Validator.java:1178)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:704)
	at org.eclipse.wst.validation.internal.ValManager$1.visit(ValManager.java:665)
	at org.eclipse.wst.validation.internal.ValManager.accept(ValManager.java:810)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:669)
	at org.eclipse.wst.validation.internal.ValidationRunner.execute(ValidationRunner.java:134)
	at org.eclipse.wst.validation.internal.ValidationRunner.validate(ValidationRunner.java:68)
	at org.eclipse.wst.validation.ui.internal.ManualValidationRunner.runInWorkspace(ManualValidationRunner.java:83)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.m2e.wtp.MavenWtpPlugin cannot be found by com.ibm.etools.maven.javaee.ui_1.1.405.v20221119_0548
	... 14 more

eclipse.buildId=4.27.0.20230309-1200
java.version=19.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/wnm3/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -clean -product org.eclipse.epp.package.jee.product -data file:/Users/wnm3/csnext/aiden/ -clean -product org.eclipse.epp.package.jee.product -keyring /Users/wnm3/.eclipse_keyring

**Comment by wnm3** [comment]
I reinstalled Eclipse 2023-03 and just the Open Liberty Tools from the zip [here](https://github.com/OpenLiberty/open-liberty-tools/issues/460#issuecomment-1499049167) in #460 and Validation Error went away. However, the pom.xml and two .sh files now display with an odd red dot. There are no problems reported though, and I can manually validate these files (which generated the error above before).
<img width="284" alt="image" src="https://github.com/OpenLiberty/open-liberty-tools/assets/1359024/bc425c71-0485-4e0c-98bc-985f47f115c5">

**Comment by pnickoll** [comment]
@wnm3 I believe this red dot issue has been fixed in 2023-09 (see https://github.com/OpenLiberty/open-liberty-tools/issues/485) . Can you check please?

**Comment by pnickoll** [comment]
Closing this as I believe this is fixed in WDT 23.2. Please reopen if you have issues
