### ISSUE TITLE
Delete the Gradle server and runtime if the Gradle project is deleted

### ISSUE THREAD

**Issue by eharris369** [OpenLiberty/open-liberty-tools#65]
The Gradle server and runtime associated with a Gradle project should be deleted if the project is deleted.

**Comment by eharris369** [comment]
I am getting this exception when I delete the project sometimes and the server and runtime don't get deleted.

java.lang.Exception: Failed to stop server: webexample
	at com.ibm.ws.st.liberty.buildplugin.integration.manager.internal.AbstractLibertyManager$DeletionJob.ensureServersStopped(AbstractLibertyManager.java:922)
	at com.ibm.ws.st.liberty.buildplugin.integration.manager.internal.AbstractLibertyManager$DeletionJob.performDelete(AbstractLibertyManager.java:844)
	at com.ibm.ws.st.liberty.buildplugin.integration.manager.internal.AbstractLibertyManager$DeletionJob.runInWorkspace(AbstractLibertyManager.java:817)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by keithchong** [comment]
I can reproduce this also with a Maven project (w/ Maven Liberty Server)

**Comment by eharris369** [comment]
This is fixed now.
